
class AWSConfig:
    API_KEY = "XXXXXXXXXX"
    # API_KEY = "XXXXXXXXXX"
    API_KEY = "XXXXXXXXXX"
    API_SECRET = "XXXXXXXXXX/YUNsz8h054MHRJAzPgNe"
    # API_SECRET = "XXXXXXXXXX"
    API_SECRET = "XXXXXXXXXX"
